// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';<
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-h-mrCAQTix8wvZluUQP8ED3wEBwWr0',
    appId: '1:830111814959:web:5578e98a7162617de23dda',
    messagingSenderId: '830111814959',
    projectId: 'petleo-test',
    authDomain: 'petleo-test.firebaseapp.com',
    storageBucket: 'petleo-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMeeQnSMb8HYd6wdI6fU63VXRA5VwkhU',
    appId: '1:830111814959:android:f3fdc7ea8e2d5e49e23dda',
    messagingSenderId: '830111814959',
    projectId: 'petleo-test',
    storageBucket: 'petleo-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wr42RL2k5ep3WrRiJnvaxQPz85VjBHo',
    appId: '1:830111814959:ios:4655f118b8fe7953e23dda',
    messagingSenderId: '830111814959',
    projectId: 'petleo-test',
    storageBucket: 'petleo-test.appspot.com',
    iosBundleId: 'com.example.petleoTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3wr42RL2k5ep3WrRiJnvaxQPz85VjBHo',
    appId: '1:830111814959:ios:4655f118b8fe7953e23dda',
    messagingSenderId: '830111814959',
    projectId: 'petleo-test',
    storageBucket: 'petleo-test.appspot.com',
    iosBundleId: 'com.example.petleoTest',
  );
}
